name: run tests

on:
  push:
  pull_request:

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  macos:
    runs-on: macos-15
    if: ${{ github.repository == 'espressomd/espresso' }}
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: macos
          save: ${{ github.ref == 'refs/heads/python' }}
      - name: Get runner specifications
        run: system_profiler SPHardwareDataType
      - run: |
         brew install boost boost-mpi fftw
         python3 -m venv venv
         . venv/bin/activate
         pip3 install -c requirements.txt cython numpy scipy packaging
         deactivate
        shell: bash
      - name: Build and check
        uses: ./.github/actions/build_and_check
        env:
          build_procs: 3
          check_procs: 3
          with_ccache: 'true'

  debian:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/espressomd/docker/debian:77a3823c5c4c2338c39eb0e0f054b5802f0f2a5e-base-layer
      credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.github_token }}
      options: --cpus 4
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: debian
          save: ${{ github.ref == 'refs/heads/python' || ( github.repository != 'espressomd/espresso' && ! startsWith(github.ref, 'refs/pull') ) }}
      - name: Setup Git environment
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Get runner specifications
        run: lscpu | egrep 'Model name|Socket|Thread|NUMA|CPU\(s\)'
      - name: Build and check
        uses: ./.github/actions/build_and_check
        env:
          build_procs: 4
          check_procs: 4
          CC: 'gcc-12'
          CXX: 'g++-12'
          myconfig: 'maxset'
          with_ccache: 'true'
          with_cuda: 'false'
          with_hdf5: 'true'
          with_fftw: 'true'
          with_gsl: 'false'
          with_scafacos: 'false'
          with_stokesian_dynamics: 'false'
          make_check_unit_tests: 'true'
          make_check_python: 'false'
          OMPI_ALLOW_RUN_AS_ROOT: 1
          OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1

  ubuntu:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'espressomd/espresso' }}
    container:
      image: ghcr.io/espressomd/docker/ubuntu-wo-dependencies:77a3823c5c4c2338c39eb0e0f054b5802f0f2a5e-base-layer
      credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.github_token }}
      options: --cpus 4
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ubuntu
          save: ${{ github.ref == 'refs/heads/python' }}
      - name: Setup Git environment
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Get runner specifications
        run: lscpu | egrep 'Model name|Socket|Thread|NUMA|CPU\(s\)'
      - name: Build and check
        uses: ./.github/actions/build_and_check
        env:
          build_procs: 4
          check_procs: 4
          CC: 'gcc-13'
          CXX: 'g++-13'
          myconfig: 'maxset'
          with_ccache: 'true'
          with_cuda: 'false'
          with_hdf5: 'false'
          with_fftw: 'false'
          with_gsl: 'false'
          with_scafacos: 'false'
          with_stokesian_dynamics: 'false'
          make_check_unit_tests: 'false'
          make_check_python: 'false'
          OMPI_ALLOW_RUN_AS_ROOT: 1
          OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
